version: "3.9"

services:
  posti:
    image: ghcr.io/pbuzdygan/posti:latest
    container_name: posti
    restart: unless-stopped
    ports:
      - "8012:8000"
    volumes:
      - ./data:/app/data
